language: node_js
node_js: stable
cache:
  apt: true
  directories:
    - node_modules

before_install:
  - npm install hexo-cli -g
  - npm install hexo-deployer-git --save

install:
  - npm install
  - npm rebuild node-sass --force

script:
  - hexo clean
  - hexo generate
  - git config user.name "TenantTim"
  - git config user.email "t-i.m@outlook.com"
  - sed -i "s/git@github.com:/https:\/\/${GithubAccessToken}@github.com\//" _config.yml
  - hexo deploy

branches:
  only:
  - hexo