language: node_js
node_js: stable
cache:
  apt: true
  directories:
    - node_modules

before_install:
  - npm install hexo-cli -g

install:
  - npm install
  - npm rebuild node-sass --force

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GithubAccessToken
  local-dir: public
  target-branch: master
  on:
    branch: hexo

branches:
  only:
  - hexo